service: retro-drop-api

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs8.10
  stage: production
  profile: retro-drop
  memorySize: 256 # We're not doing anything complicated here.

# Routing logic is handled by express.
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      NODE_ENV: production

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.retrodropapp.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: '*.retrodropapp.com'